sudo: required
services:
  - docker

before_install:
  - docker build -t mathan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mathan/react-test npm test

after_success:
  - docker build -t mathan/multi-client ./client
  - docker build -t mathan/multi-nginx ./nginx
  - docker build -t mathan/multi-server ./server
  - docker build -t mathan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mathan/multi-client
  - docker push mathan/multi-nginx
  - docker push mathan/multi-server
  - docker push mathan/multi-worker
